docschina/babeljs.io

docs/usage/polyfill.md

/docs/usage/polyfill.md 中文翻译工作，需求任务见 #10

translate /docs/usage/polyfill.md into Chinese

---

_data/tools.yml
docs/setup.md

Complete the translation of setup.md

---

_includes/tools/babel_register/usage.md

Complete the translation of _includes/tools/babel_register

---

_includes/tools/babel_cli/install.md
_includes/tools/babel_cli/usage.md

* 翻译 /_includes/tools/babel_cli 下所有文件为中文
* 详细任务见 #21

translate files in /_includes/tools/babel_cli into Chinese

---

env.md

update: translate /env.md into Chinese

---

_includes/tools/brunch/usage.md

Complete the translation of _includes/tools/brunch 

---

_includes/tools/ava/install.md
_includes/tools/ava/usage.md
_includes/tools/babel_node_debug/usage.md
_includes/tools/connect/usage.md
_includes/tools/dotnet/install.md
_includes/tools/dotnet/usage.md
_includes/tools/duo/usage.md
_includes/tools/ember/usage.md
_includes/tools/fly/usage.md
_includes/tools/gobble/usage.md
_includes/tools/grunt/usage.md
_includes/tools/gulp/usage.md
_includes/tools/jasmine/usage.md
_includes/tools/jest/usage.md
_includes/tools/jspm/install.md
_includes/tools/jspm/usage.md
_includes/tools/karma/usage.md
_includes/tools/lab/usage.md
_includes/tools/make/install.md
env.md

中文翻译工作，具体涉及子任务如下
* update: translate /_includes/tools/ava into Chinese
* update: translate /_includes/tools/babel_node_debug into Chinese
* update: translate /_includes/tools/connect into Chinese
* update: translate /_includes/tools/dotnet into Chinese
* update: translate /_includes/tools/duo into Chinese
* update: translate /_includes/tools/ember into Chinese
* update: translate /_includes/tools/fly into Chinese
* update: translate /_includes/tools/gobble into Chinese
* update: translate /_includes/tools/grunt into Chinese
* update: translate /_includes/tools/gulp into Chinese
* update: translate /_includes/tools/jasmine into Chinese
* update: translate /_includes/tools/jest into Chinese
* update: translate /_includes/tools/jspm into Chinese
* update: translate /_includes/tools/karma …

tools 目录下部分翻译工作汇总

---

_includes/tools/node/usage.md
_includes/tools/nodemon/usage.md
_includes/tools/pug/usage.md
_includes/tools/rails/usage.md
_includes/tools/ruby/usage.md
_includes/tools/sails/usage.md
_includes/tools/start/usage.md
_includes/tools/webpack/usage.md
_includes/tools/webstorm/usage.md

中文翻译工作，具体涉及子任务如下
* update: translate /_includes/tools/node into Chinese
* update: translate /_includes/tools/nodemon into Chinese
* update: translate /_includes/tools/pug into Chinese
* update: translate /_includes/tools/rails into Chinese
* update: translate /_includes/tools/ruby into Chinese
* update: translate /_includes/tools/sails into Chinese
* update: translate /_includes/tools/webpack into Chinese
* update: translate /_includes/tools/webstorm into Chinese
* _includes/tools/start/usage.md
Issues 参见 #65 #64 #63 #61 #89 #52 #53 #47 #49

tools 目录下所有剩余翻译工作汇总

---

_includes/tools/broccoli/usage.md
_includes/tools/browserify/usage.md
_includes/tools/brunch/usage.md
_includes/tools/msbuild/install.md
_includes/tools/msbuild/usage.md
_includes/tools/requirejs/usage.md
_includes/tools/rollup/install.md
_includes/tools/rollup/usage.md
_includes/tools/sprockets/usage.md
_includes/tools/webpack2/usage.md

中文翻译工作，具体涉及子任务如下
* update: translate /_includes/tools/msbuild into Chinese
* update: translate /_includes/tools/requirejs into Chinese
* update: translate /_includes/tools/rollup into Chinese
* update: translate /_includes/tools/sprockets into Chinese
* update: translate /_includes/tools/webpack2 into Chinese
修复关于 repo 翻译不统一问题
Issues 参见 #46 #45 #44  #43 #42

tools 目录下部分剩余翻译工作汇总

---

_config.yml
_includes/head.html
_layouts/default.html

首页标题修改后为：Babel  · 用于编写下一代 JavaScript 的编译器 | Babel中文网
内容页标题为：我是标题 | Babel中文网

SEO，并与搜索引擎已经收录的索引保持一致

---

docs/usage/caveats.md

涉及以下文件
* `/docs/usage/caveats.md`
issue #12

update: traslate #12 

---

docs/plugins.md

Complete the translation of docs/plugins.md

---

_includes/readmes/babel-preset-react.md

update: translate babel-preset-react into Chinese (#88 )

---

_includes/readmes/babel-cli.md

update: translate babel-cli into Chinese

---

docs/usage/cli.md

任务 issue 详见 https://github.com/docschina/babeljs.io/issues/11

update: translate /docs/usage/cli.md into Chinese

---

_includes/readmes/babel-preset-stage-0.md

任务 issue 详见 https://github.com/docschina/babeljs.io/issues/84

update: translate /readmes/babel-preset-stage-0.md into Chinese

---

_includes/readmes/babel-plugin-check-es2015-constants.md

babel-plugin-check-es2015-constants翻译完成

---

_includes/readmes/babel-preset-stage-1.md

任务 issue 详见 https://github.com/docschina/babeljs.io/issues/85

update: translate /readmes/babel-preset-stage-1.md into Chinese

---

_includes/readmes/babel-preset-latest.md

translate babel-preset-latest to Chinese

---

_includes/readmes/babel-core.md

update: translate _includes/readmes/babel-core.md into Chinese

---

_includes/readmes/babel-preset-stage-3.md

任务 issue 详见 https://github.com/docschina/babeljs.io/issues/87

update: translate /readmes/babel-preset-stage-3.md into Chinese

---

docs/core-packages.md

core-packages

---

_includes/readmes/babel-plugin-minify-builtins.md
_includes/readmes/babel-plugin-minify-constant-folding.md
_includes/readmes/babel-plugin-minify-dead-code-elimination.md
_includes/readmes/babel-plugin-minify-flip-comparisons.md
_includes/readmes/babel-plugin-minify-guarded-expressions.md

中文翻译工作，具体涉及子任务如下:
* update: translate /_includes/readmes/babel-plugin-minify-builtins.md into Chinese
* update: translate /_includes/readmes/babel-plugin-minify-constant-folding.md into Chinese
* update: translate /_includes/readmes/babel-plugin-minify-dead-code-elimination.md into Chinese
* update: translate /_includes/readmes/babel-plugin-minify-flip-comparisons.md into Chinese
* update: translate /_includes/readmes/babel-plugin-minify-guarded-expressions.md into Chinese
Issues 参见 #110 #111 #113 #116 #117

update: translate a part of /_includes/readmes/ directory into chinese

---

docs/plugins/preset-latest.md

update: translate /docs/plugins/preset-latest.md into Chinese

---

docs/plugins/preset-stage-0.md

update: translate /docs/plugins/preset-stage-0.md into Chinese

---

learn-es2015.md

#3 修正了一些格式问题、翻译上的错别字、遗漏的翻译以及一些理解上的误区

fixed: fix /learn-es2015.md translation

---

_includes/readmes/babel-preset-env.md

translate babel-preset-env into Chinese

---

docs/plugins/preset-stage-1.md
docs/plugins/preset-stage-2.md
docs/plugins/preset-stage-3.md

translate preset-stage-1、2&3 into Chinese

---

docs/plugins/syntax-async-functions.md
docs/plugins/syntax-async-generators.md

translate syntax-async-functions & generator into Chinese

---

docs/plugins/preset-env.md

update: translate docs/plugins/preset-env.md into Chinese

---

index.md

校对了 index.md 中的中英文标点符号/翻译词句/语序等，有些地方统一了翻译标准，比如 plugin 统一为 插件。Issue 见 #4

update: proofread index.md CN

---

docs/setup.md

update: proofread docs/setup.md CN

---

docs/editors.md

update: proofread docs/editors.md CN

---

docs/usage/cli.md

update: proofread docs/cli.md CN

---

docs/core-packages.md

 update: proofread docs/core-packages.md CN

---

_includes/readmes/babel-core.md

 update: proofread _includes/readmes/babel-core.md CN

---

_includes/tools/browserify/usage.md
_includes/tools/brunch/usage.md

本次校对 PR 包含两个 issue 分别为 #34 和 #35

update: proofread brunch and browserify in _includes/tools folder CN

---

docs/plugins/preset-es2016.md

update: translate /docs/plugins/preset-es2016.md into Chinese
